### ISSUE TITLE
User Story #8 - Burger Menu Button

### ISSUE THREAD

**Issue by JannikUekoetter** [JannikUekoetter/capstone-project#10]
## Value Proposition

As a user i would like to have the possibility to navigate the app via a menu so that i can reach all areas.

## Discription

The navigation is to be realized via a burger menu. For this you need a button on all pages that opens the burger menu when you click on it

// Insert Wire Frame
![Bildschirmfoto 2022-10-17 um 12 09 21](https://user-images.githubusercontent.com/101580574/196151244-0f6a212a-8474-4f90-a867-53bed1fb0ccb.png)

## Acception Criteria

- [ ] Burger menu button is visible on each page
- [ ] click to open the burger menu

## Tasks

- [ ] include burger menu icon in every page of the app
- [ ] burger menu button with on click functionality so that it leads to the right areas of the app
- [ ] install routing and thus assign the correct paths

**Comment by Kheirah** [comment]
Clear and bite-sized feature, very good!👍

I'd add that you can click on the already opened menu as to close it again. That would be an additional acceptance criterion, something like "click to close the burger menu".
