### ISSUE TITLE
User Story # 9 - Contact Page

### ISSUE THREAD

**Issue by JannikUekoetter** [JannikUekoetter/capstone-project#11]
## Value Proposition

As a user I would like a contact page so I can contact the person who found an item of mine.

## Discription

Contact page where I see a picture of the item, have a field for a message and a submit button with which I can send the message.

// Insert Wire Frame
![Bildschirmfoto 2022-10-17 um 16 48 36](https://user-images.githubusercontent.com/101580574/196209029-5345a3f1-d65d-4432-9f31-0b3e7362725c.png)

## Acception Criteria

- [ ] Header must be visible
- [ ] I need a picture of the item
- [ ] An input field is needed to be able to send a message
- [ ] I need a submit button so I can send the request

## Tasks

- [ ] Write header
- [ ] Implement picture of item
- [ ] Write input field
- [ ] Write basic submit button (functionality will be implemented in another story)

**Comment by Roland-Hufnagel** [comment]
Hey Jannik, are you sure, you want to implement the picture at this time? Do you have pictures right now in your fake - DB, that you can use? Then it is okay. 
Maybe at another point in your application a button is needed, that routes to this page?

**Comment by Roland-Hufnagel** [comment]
You can give the user a role here too (like in the other story 'a user, that lost an item').

**Comment by JannikUekoetter** [comment]
Hey Roland, yes I have pictures included in my DB, but thank you for the hint! :)
