### ISSUE TITLE
Add Routing for Contact Button on Item Detail Page

### ISSUE THREAD

**Issue by JannikUekoetter** [JannikUekoetter/capstone-project#16]
## Value Proposition

As a user i would like to be able to click on the button and come out at the contact form.

## Discription
I have already written a Contact Button and now need to add functionality to it so that it sets the routing to the correct endpoint (Contact Page).

## Acception Criteria

- [ ] Button is visible and has functionality
- [ ] Accessibility is implemented

## Tasks

- [ ] Write functionality and routing for the button
- [ ] Make the button accessible
