### ISSUE TITLE
Add routing to project and place components accordingly

### ISSUE THREAD

**Issue by JannikUekoetter** [JannikUekoetter/capstone-project#17]
## Value Proposition

As a user, I want to be able to find the components at the appropriate locations on the routes.

## Discription

All routes must be checked and set correctly. Then all components must be placed on the correct routes and these routes must be linked to the buttons in the burger menu.

## Acception Criteria

- [ ] all components intended for this purpose have been given a route and have been placed in it
- [ ] the routes can be accessed via the burger menu

## Tasks

- [ ] Set route for every component that is to be placed at the end of a specific route
- [ ] consider which components need routes
- [ ] connect the routes with the buttons in the burger menu
- [ ] test whether all components can be reached via the intended routes
