### ISSUE TITLE
Add overall Routing to all parts of the App

### ISSUE THREAD

**Issue by JannikUekoetter** [JannikUekoetter/capstone-project#19]
## Value Proposition

As a user I want to be able to reach all areas of the app via URL or routing so that I can use all functionalities and receive all available information.

## Discription

// Insert Wire Frame

## Acception Criteria

- [ ] all buttons in the burger menu are linked to the correct route
- [ ] all buttons that should have this functionality include the correct routing
- [ ] the matching routes are displayed in the urls

## Tasks
- [ ] create all necessary routes in the pages folder in the project
- [ ] write the appropriate routing functionality for all buttons in all areas of the app
- [ ] write the appropriate routing functionality for all buttons of the burger menu
