### ISSUE TITLE
User Story 1 - Rework (MVP?)

### ISSUE THREAD

**Issue by JannikUekoetter** [JannikUekoetter/capstone-project#3]
## Value Proposition

As a  user, I want  to see all items on the main page so that I can get an overview.

## Discription

items should be displayed on the start page 

// Insert Wire Frame
![Bildschirmfoto 2022-10-15 um 16 02 38](https://user-images.githubusercontent.com/101580574/195990647-7f6e28c6-a0f6-4725-a514-6873e53e616a.png)

## Acception Criteria

- [ ] individual items are to be displayed as tiles

## Tasks

- [ ] I need an array of individual items
- [ ] These items should be displayed on the page
- [ ] With the map method these individual tiles are to be assigned
