### ISSUE TITLE
User Story #2 - Search Bar

### ISSUE THREAD

**Issue by JannikUekoetter** [JannikUekoetter/capstone-project#4]
## Value Proposition

As a user, I want search for items so that so that I can find things faster.

## Discription
We need a search function to find individual items.

// Insert Wire Frame
![Bildschirmfoto 2022-10-15 um 16 12 59](https://user-images.githubusercontent.com/101580574/195991130-d88ece9c-3006-43e1-90b7-b9f65f46b77d.png)

## Acception Criteria

- [ ] user can use search function that narrows down the results displayed when entering keywords
- [ ] user can type into the input field and gets result immediately

## Tasks

- [ ] we write an input field
- [ ] here the functionality of a search function must be connected with the input field
- [ ] we need a default text in the input field of the search function

**Comment by F-Kirchhoff** [comment]
Your user story is okay, please specify in more detail how the search term is used for finding the elements, is it filtered for name, type or something else? Please reword the Tasks without a subject:
- create an serach bar component
- add search bar icon
- implement filtering of lost items based on search query
- etc.

**Comment by F-Kirchhoff** [comment]
Oh and please remove the //insert wire frame :D

**Comment by AHen-C0de** [comment]
Hey,
the Value Proposition got a bit messy: "...I want search for items so that so that..." ;)
