### ISSUE TITLE
User Story #3 - Detail Page

### ISSUE THREAD

**Issue by JannikUekoetter** [JannikUekoetter/capstone-project#5]
## Value Proposition

As a user that lost an item, I want to able to see an item in detail so that I can find out if it is my own.

## Discription

For this we need a detail page for the items, so that more information can be provided.

// Insert Wire Frame
![Bildschirmfoto 2022-10-17 um 11 11 59](https://user-images.githubusercontent.com/101580574/196138931-9c5579df-8385-4083-9d52-37dce4c1f7a3.png)

## Acception Criteria

- [ ] We need a representation of the photo of the item
- [ ] listed here
- [ ] and another one

## Tasks

- [ ] tasks to achieve the functionalities
- [ ] we need a field for a description
- [ ] to be executed by developer
- [ ] we need a headline

**Comment by gacsphere** [comment]
Hi Jannik,
your wireframe looks a bit like a form because there are two empty fields for description and location. Those look like input fields because there is no content displayed. As acception creteria you say, that those two infos shall be displayed, which is very good! Your wireframe just doesn't match that. But as it's in your acceptance creteria, I guess you meant it right.
I'm not sure about the button. Does it have the functionality yet or does that come in a further step? If the functionality comes in a further step, you shouldn't display the button here yet.

**Comment by JannikUekoetter** [comment]
Danke @gacsphere :)
