### ISSUE TITLE
User Story #4 - Contact Button on Detail Page

### ISSUE THREAD

**Issue by JannikUekoetter** [JannikUekoetter/capstone-project#6]
## Value Proposition

As a user that lost an item, I want to be able to make contact so that I can retreive my item.

## Discription

// Insert Wire Frame
![Bildschirmfoto 2022-10-17 um 11 22 08](https://user-images.githubusercontent.com/101580574/196140998-2042b7b1-541b-40b2-b95f-84ad5b25de4e.png)

## Acception Criteria

- [ ] we need a button to make contact
- [ ] the button should lead to a contact form
- [ ] click should contain a functionality here

## Tasks

- [ ] write visual basic structure of the button 
- [ ] add functionality to the button so that it leads to the contact form

**Comment by Roland-Hufnagel** [comment]
Okay. Here is the starting point. Do you really need two Stories for that? Because here it is only the button and it belongs to the other userstory. I would recommend to put it together.
