### ISSUE TITLE
User Story #5 - Lost Something? Item Page

### ISSUE THREAD

**Issue by JannikUekoetter** [JannikUekoetter/capstone-project#7]
## Value Proposition

As a user who has lost an item I would like to have the possibility to add it into the app so I can find it again.

## Discription

A site that allows to add a description, location and photo of an lost object.

// Insert Wire Frame
![Bildschirmfoto 2022-10-17 um 11 38 04](https://user-images.githubusercontent.com/101580574/196144366-d65246b5-9e00-4aea-b49f-f7b891dd27a4.png)

## Acception Criteria

- [ ] header displayed
- [ ] description input visible
- [ ] submit button (without functionality) visible

## Tasks

- [ ] write basic header
- [ ] write description input field
- [ ] write basic button (without functionality)
- [ ] new item needs random generated ID with nano(id)
