### ISSUE TITLE
User Story #7 - Lost Something? Item Page - Add photo + location

### ISSUE THREAD

**Issue by JannikUekoetter** [JannikUekoetter/capstone-project#9]
## Value Proposition

As a user I would like to add a photo of the lost item and specify the location so that the description is more detailed.

## Discription

Possibility to upload a photo via a click + a field for the location of the item

![Bildschirmfoto 2022-10-17 um 12 00 55](https://user-images.githubusercontent.com/101580574/196149437-d1f02a35-6e87-4f95-9bfc-f7ee4a03d7a0.png)

## Acception Criteria

- [ ] a field where you can upload a photo
- [ ] there is a field with the location visible
- [ ] the location can be specified via an input field and will appear later on the detail page of the item

## Tasks
- [ ] write outer appearance of the upload button
- [ ] the possibility to upload via <input type="media" />
- [ ] I write an input field for the location
- [ ] when i click submit the data will be sent to the detail page
- [ ] store data in local db

**Comment by philmetscher** [comment]
Hey,
as the first task I would always write the creation of a new feature
Rewrite suggestion (Task1): "add a `Upload Button component`"

Task2: why you need a framework? Hint: `<input type="media" />`

Task4: maybe describe how the data will be stored? localStorage, sessionStorage, db?
